from typing import List
import pandas as pd
from pydantic import BaseModel, Field
from services.llm_factory import LLMFactory


class SynthesizedResponse(BaseModel):
    thought_process: List[str] = Field(
        description="List of thought processes from AI assistant leading to the final answer"
    )
    answer: str = Field(
        description="Final answer generated by the AI assistant"
    )
    enough_context: bool = Field(
        description="Indicates whether the AI had enough context to generate a good answer"
    )

class Synthesizer:
    SYSTEM_PROMPT = """
    # Role and Purpose
    You are an AI assistant for an e-commerce FAQ system. Your task is to synthesize a coherent and helpful answer 
    based on the given question and relevant context retrieved from a knowledge database.

    # Guidelines:
    1. Provide a clear and concise answer to the question.
    2. Use only the information from the relevant context to support your answer.
    3. The context is retrieved based on cosine similarity, so some information might be missing or irrelevant.
    4. Be transparent when there is insufficient information to fully answer the question.
    5. Do not make up or infer information not present in the provided context.
    6. If you cannot answer the question based on the given context, clearly state that.
    7. Maintain a helpful and professional tone appropriate for customer service.
    8. Adhere strictly to company guidelines and policies by using only the provided knowledge base.
    
    Review the question from the user:
    """

    @staticmethod
    def generate_response(question: str, context: pd.DataFrame) -> SynthesizedResponse:
        context_str = Synthesizer.dataframe_to_json(
            context,
            columns_to_keep=["content", "category"]
        )

        messages =[
            {"role": "user", "content": f"# User question:\n{question}"},
            {"role": "system", "content": Synthesizer.SYSTEM_PROMPT},
            {"role": "assistant", 
             "content": f"# Retrieved information:\n{context_str}"}
        ]

        llm = LLMFactory("openai")
        return llm.create_completion(
            response_model = SynthesizedResponse,
            messages = messages
        )
    
    @staticmethod
    def dataframe_to_json(
        context: pd.DataFrame,
        columns_to_keep: List[str]
    )-> str:
        return context[columns_to_keep].to_json(orient="records", indent=2)


